import time
from colorama import init
from colorama import Fore, Back, Style
init()

while True:
    print("                                                                                   " + (Fore.RED) + "|" + (Fore.YELLOW) + "----------" + (Fore.CYAN) + "|")
    time.sleep(0.1)
    print("                                                                                    " + (Fore.RED) + "[" + (Fore.YELLOW) + "--------" + (Fore.CYAN) + "]")
    time.sleep(0.1)
    print("                                                                                     " + (Fore.RED) + "[" + (Fore.YELLOW) + "------" + (Fore.CYAN) + "]")
    time.sleep(0.1)
    print("                                                                                      " + (Fore.RED) + "[" + (Fore.YELLOW) + "----" + (Fore.CYAN) + "]")
    time.sleep(0.1)
    print("                                                                                       " + (Fore.RED) + "[" + (Fore.YELLOW) + "--" + (Fore.CYAN) + "]")
    time.sleep(0.1)
    print("                                                                                        " + (Fore.RED) + "[" + (Fore.CYAN) + "]")
    time.sleep(0.1)
    print("                                                                                        " + (Fore.CYAN) + "]" + (Fore.RED) + "[")
    time.sleep(0.1)
    print("                                                                                       " + (Fore.CYAN) + "]" + (Fore.YELLOW) + "--" + (Fore.RED) + "[")
    time.sleep(0.1)
    print("                                                                                      " + (Fore.CYAN) + "]" + (Fore.YELLOW) + "----" + (Fore.RED) + "[")
    time.sleep(0.1)
    print("                                                                                     " + (Fore.CYAN) + "]" + (Fore.YELLOW) + "------" + (Fore.RED) + "[")
    time.sleep(0.1)
    print("                                                                                    " + (Fore.CYAN) + "]" + (Fore.YELLOW) + "--------" + (Fore.RED) + "[")
    time.sleep(0.1)
    print("                                                                                   " + (Fore.CYAN) + "|" + (Fore.YELLOW) + "----------" + (Fore.RED) + "|")
    time.sleep(0.1)
    print("                                                                                   " + (Fore.CYAN) + "|" + (Fore.YELLOW) + "----------" + (Fore.RED) + "|")
    time.sleep(0.1)
    print("                                                                                   " + (Fore.CYAN) + "|" + (Fore.YELLOW) + "----------" + (Fore.RED) + "|")
    time.sleep(0.1)
    print("                                                                                    " + (Fore.CYAN) + "[" + (Fore.YELLOW) + "--------" + (Fore.RED) + "]")
    time.sleep(0.1)
    print("                                                                                     " + (Fore.CYAN) + "[" + (Fore.YELLOW) + "------" + (Fore.RED) + "]")
    time.sleep(0.1)
    print("                                                                                      " + (Fore.CYAN) + "[" + (Fore.YELLOW) + "----" + (Fore.RED) + "]")
    time.sleep(0.1)
    print("                                                                                       " + (Fore.CYAN) + "[" + (Fore.YELLOW) + "--" + (Fore.RED) + "]")
    time.sleep(0.1)
    print("                                                                                        " + (Fore.CYAN) + "[" + (Fore.RED) + "]")
    time.sleep(0.1)
    print("                                                                                        " + (Fore.RED) + "]" + (Fore.CYAN) + "[")
    time.sleep(0.1)
    print("                                                                                       " + (Fore.RED) + "]" + (Fore.YELLOW) + "--" + (Fore.CYAN) + "[")
    time.sleep(0.1)
    print("                                                                                      " + (Fore.RED) + "]" + (Fore.YELLOW) + "----" + (Fore.CYAN) + "[")
    time.sleep(0.1)
    print("                                                                                     " + (Fore.RED) + "]" + (Fore.YELLOW) + "------" + (Fore.CYAN) + "[")
    time.sleep(0.1)
    print("                                                                                    " + (Fore.RED) + "]" + (Fore.YELLOW) + "--------" + (Fore.CYAN) + "[")
    time.sleep(0.1)
    print("                                                                                   " + (Fore.RED) + "|" + (Fore.YELLOW) + "----------" + (Fore.CYAN) + "|")
    time.sleep(0.1)
    print("                                                                                   " + (Fore.RED) + "|" + (Fore.YELLOW) + "----------" + (Fore.CYAN) + "|")